runtime: python312  # 使用 Python 3.9 运行环境

entrypoint: gunicorn -b :$PORT myproject.wsgi:application  # 应用入口点

handlers:  # URL 处理规则
- url: /static
  static_dir: static/
- url: /.*
  script: auto

env_variables:  # 环境变量
  DJANGO_SETTINGS_MODULE: 'myproject.settings'
  DB_NAME: 'postgres'
  DB_USER: 'postgres'
  DB_PASSWORD: 'your_password_here'
  DB_HOST: '34.94.226.247'
  DB_PORT: '5432'

