# Generated by Django 4.2.25 on 2025-10-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(default="general", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "interest_areas",
            },
        ),
    ]
