# Generated by Django 4.2.25 on 2025-10-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_interestarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="description_zh",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="name_en",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="concept",
            name="name_zh",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="interestarea",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interestarea",
            name="description_zh",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interestarea",
            name="display_name_en",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="interestarea",
            name="display_name_zh",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
