# Generated by Django 4.2.25 on 2025-10-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0003_concept_description_en_concept_description_zh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("zh", "Chinese")],
                default="en",
                max_length=2,
            ),
        ),
    ]
