# Generated by Django 4.2.25 on 2025-10-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0004_alter_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="sql_schema",
            field=models.TextField(),
        ),
    ]
